name: Test
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        otp: [26.2]
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: CONFIGURE OTP & ELIXIR
      uses: actions/setup-elixir@v1
      with:
        otp-version: ${{ matrix.otp }}
        elixir-version: 1.16.3
    - name: DIALYZE
      run: make dialyze
    - name: TEST
      run: make tests
    - name: ON FAILRUE ARCHIVE TESTS LOGS
      if: failure()
      run: |
        make ct-logs-archive
    - name: ON FAILURE UPLOAD TESTS LOGS ARTIFACT
      uses: actions/upload-artifact@v2-preview
      if: failure()
      with:
        name: ct-logs
        path: "*-ct-logs-*.tar.xz"
